apiVersion: apps/v1
kind: Deployment
metadata:
  name: ConferenceApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ConferenceApp
  template:
    metadata:
      labels:
        app: ConferenceApp
    spec:
      containers:
        - name: ConferenceApp
          image: sachithlakmal/conference-app:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 8081
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"       # Memory request
              ephemeral-storage: 1Gi
            limits:
              memory: "512Mi"       # Memory limit
          volumeMounts:
            - name: config-volume
              mountPath: /home/config
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 1
      volumes:
        - name: config-volume
          configMap:
            name: application-config